export const SALES_SOURCE_HEADERS = {
  "s no": "sNo",
  "s no.": "sNo",
  "sr no": "sNo",
  "sr no.": "sNo",
  branch: "branch",
  invoice: "invoice",
  "inv no": "invoice",
  "inv no.": "invoice",
  "posting date": "postingDate",
  "invoice date": "postingDate",
  "customers name": "customersName",
  "customer name": "customersName",
  "customers gstin": "customersGstin",
  "customer gstin": "customersGstin",
  "customers gstin/uin": "customersGstin",
  "sales order": "salesOrder",
  "delivery note": "deliveryNote",
  "purchase order": "purchaseOrder",
  "net total": "netTotal",
  "taxable amount": "netTotal",
  "output tax cgst": "outputTaxCgst",
  "output tax sgst": "outputTaxSgst",
  "output tax igst": "outputTaxIgst",
  "cgst": "outputTaxCgst",
  "sgst": "outputTaxSgst",
  "igst": "outputTaxIgst",
  "grand total": "grandTotal",
};

export const SALES_REQUIRED_HEADER_KEYS = [
  "invoice",
  "postingDate",
  "netTotal",
  "grandTotal",
];

export const SALES_OUTPUT_COLUMNS = [
  "Invoice date",
  "Voucher Type",
  "Voucher No.",
  "Invoice No.",
  "Ledger",
  "Customer Name",
  "Customer GSTIN",
  "Taxable Amount",
  "CGST Tax",
  "SGST Tax",
  "IGST Tax",
  "Round OFF DR",
  "Round OFF CR",
  "Grand Total",
];
